sequenceDiagram
    actor Initiator
    actor UBOs
    participant EUDIWallet_Initiator
    participant Company_Wallet
    participant Bank_System
    participant Bank_Wallet

    activate Initiator
    Initiator ->>+Bank_System: Trigger open business account & provide the required information (eubw endpoint)
    Bank_System<<->>Bank_Wallet: generate request to identity initiator(PID)
    Bank_System->>+Initiator: Request PID (qrcode)
    Initiator->>+EUDIWallet_Initiator: Scan the code
    Initiator->>+EUDIWallet_Initiator: mutual auth ( auth. certificate)
    EUDIWallet_Initiator->Bank_System : send the pid information
    Bank_System<<->>Bank_Wallet: verification of PID  (rulebook)

    Bank_System<<->>Bank_Wallet: generate request for EBWOID&EUCC
    Bank_System->>+Company_Wallet:  request legal entity identification 
    Company_Wallet->>+Company_Wallet: check the request authorization 
    Bank_System<<->>Company_Wallet: mutual authentification ( exchange EBW OID & EUCC )
    Bank_System<<->>Bank_Wallet: verification of EBW OID & EUCC(rulebook )

    opt national cases and initiator is not a legal repr (not in EUCC)
        Bank_System<<->>Bank_Wallet: generate request for EU POA 
        Bank_System<<->>Company_Wallet: request & present EU PoA
        Bank_System<<->>Bank_Wallet: verification of EU POA  (rulebook )
        Bank_System<<->>Bank_Wallet: context validation of EU PoA (scope validation)
    end

    opt cross boarder cases
        Note right of Bank_System:  Important: registration in the national registers
        Note right of Bank_System:  TODO Florin fill the idea of PoR = (EU POA + evidence + <br/>registration in the national register)
    end

    Bank_System<<->>Bank_Wallet: generate request for: TAX, VAT, CompanyInfo)
    Bank_System<<->>Company_Wallet:  request & present attestations
    Bank_System<<->>Bank_Wallet: verification of attestations (rulebook)

    Bank_System<<->>Bank_Wallet: generate request for OwnershipList,Controllist
    Bank_System<<->>Company_Wallet:  request & present attestations
    Bank_System<<->>Bank_Wallet: verification of attestations (rulebook)

    Bank_System<<->>Bank_Wallet: generate request for add. info: UBOList
    Bank_System<<->>Company_Wallet:  request & present attestations
    Bank_System<<->>Bank_Wallet: verification of attestations (rulebook)

    Note right of Bank_System: Perform UBO Calculation based on the OwnerShip/ControlList<br/>Cross-Check Against EUCC list and in case of discrepancies report <br/> Cross-Check Against Presented UBO List and in case of discrepancies inform<br/> Cross-Check Against UBO List from Transparency Register and in case of discrepancies report 
    Note right of Bank_System: TODO Florin describe process in detail from rulebook - verification part

    critical UBO Verification
        Bank_System<<->>Bank_System: Start UBO Identity Verification
    option type_of_identity_document available & ubo online & type=PID
        Bank_System<<->>Bank_Wallet: generate request for PID
        Bank_System<<->>UBOs: request & present PID
        Bank_System<<->>Bank_Wallet: verification of PID (rulebook verication)
        Bank_System<<->>Bank_System: verification PID data against UBO data 
    option type_of_identity_document available & ubo offline
        Note right of Bank_System:  TODO Florin fill the idea of PoA (EU PoA + evidence) from BU4
    option type_of_identity_document available & ubo online &type=mDoc, pass-ICAO (future)
        Note right of Bank_System:  TODO Florin how to validate the (mDoc, pass-ICAO-future)
    option unique_personal_identification_number available
        Note right of Bank_System: TODO Florin specify how to make the verif based on the national solution
    option other & ubo online
        Bank_System<<->>UBOs: VideoIdent - process
    end 

    opt SignatoryRights exchange
        Bank_System<<->>Bank_Wallet: generate request for signatory rights attestation 
        Bank_System<<->>Company_Wallet:  request & present 
        Bank_System<<->>Bank_Wallet: verification of SignatoryRights (rulebooks verification )

        Note right of Bank_System:  TODO SignatoryRights - Verification for persons in SR and not in EUCC (PoA?)
    end  

    critical MVP+
        Note right of Bank_System: TOPO specify the EDD, TFS and SoW attestations
    end

    Bank_System<<->>Bank_System: cross check over all attestations
    Note right of Bank_System: todo specify exact what will be cross check

    Bank_System<<->>Bank_System: Scenario2 starts - sign the contract 












