sequenceDiagram
    actor Initiator
    actor UBOs
    participant EUDIWallet_Initiator
    participant Company_Wallet
    participant Bank_System
    participant Bank_Wallet

    activate Initiator
    Initiator ->>+Bank_System: Trigger open business account & provide the required information (eubw endpoint)
    Bank_System<<->>Bank_Wallet: generate request to identity initiator(PID)
    Bank_System->>+Initiator: Request PID (qrcode)
    Initiator->>+EUDIWallet_Initiator: Scan the code
    Initiator->>+EUDIWallet_Initiator: mutual auth ( auth. certificate)
    EUDIWallet_Initiator->Bank_System : send the pid information
    Bank_System<<->>Bank_Wallet: verification of PID  (rulebook)

    Bank_System<<->>Bank_Wallet: generate request for EBWOID&EUCC
    Bank_System->>+Company_Wallet:  request legal entity identification 
    Company_Wallet->>+Company_Wallet: check the request authorization 
    Bank_System<<->>Company_Wallet: mutual authentification ( exchange EBW OID & EUCC )
    Bank_System<<->>Bank_Wallet: verification of EBW OID & EUCC(rulebook )

    opt national cases: Initiator is not a legal repr - in EUCC 
        Bank_System<<->>Bank_Wallet: generate request for EU POA 
        Bank_System<<->>Company_Wallet: request & present EU PoA
        Bank_System<<->>Bank_Wallet: verification of EU POA  (rulebook )
        Bank_System<<->>Bank_Wallet: context validation of EU PoA (scope validation)
    end

    opt cross boarder cases: Initiator must to register in the national registers
        Bank_System<<->>Bank_Wallet: generate request for PoR for initiator
        Bank_System<<->>Company_Wallet: request & present PoR
        Bank_System<<->>Bank_Wallet: verification of PoR (rulebook )
    end

    Bank_System<<->>Bank_Wallet: generate request for: TAX, VAT, CompanyInfo)
    Bank_System<<->>Company_Wallet:  request & present attestations
    Bank_System<<->>Bank_Wallet: verification of attestations (rulebook)

    Bank_System<<->>Bank_Wallet: generate request for OwnershipList,Controllist
    Bank_System<<->>Company_Wallet:  request & present attestations
    Bank_System<<->>Bank_Wallet: verification of attestations (rulebook)

    Bank_System<<->>Bank_Wallet: generate request for add. info: UBOList
    Bank_System<<->>Company_Wallet:  request & present attestations
    Bank_System<<->>Bank_Wallet: verification of attestations (rulebook)

    Note right of Bank_System: Perform UBO Calculation based on the OwnerShip/ControlList<br/>Cross-Check Against EUCC list and in case of discrepancies report <br/> Cross-Check Against Presented UBO List and in case of discrepancies inform<br/> Cross-Check Against UBO List from Transparency Register and in case of discrepancies report 

    critical UBO Verification
        Bank_System<<->>Bank_System: Start UBO Identity Verification
    option type_of_identity_document available & ubo online(PID)
        Bank_System<<->>Bank_Wallet: generate request for PID
        Bank_System<<->>UBOs: request & present PID
        Bank_System<<->>Bank_Wallet: verification of PID (rulebook verication)
        Bank_System<<->>Bank_System: verification PID data against UBO data 
    option type_of_identity_document available & ubo offline(PoA)
        Bank_System<<->>Bank_Wallet: generate request for PoA
        Bank_System<<->>Company_Wallet: request&present PoA (QEAA)
        Bank_System<<->>Bank_Wallet: verification of PoA 
        Bank_System<<->>Bank_Wallet: verification of PoA Evidence against UBO data
    option type_of_identity_document available & ubo online (mDoc, pass-ICAO-future)
        Bank_System<<->>Bank_Wallet: generate request for mDOC
        Bank_System<<->>UBOs: request & present mdoc / pass
        Bank_System<<->>Bank_Wallet: verification of mdoc/pass (rulebook verication)
        Bank_System<<->>Bank_System: verification mdoc/pass data against UBO data 
    option unique_personal_identification_number available & ubo offline
        Bank_System<<->>Bank_System: check the national database
        Bank_System<<->>Bank_System: verification identificaion data against UBO data 
    option other & ubo online
        Bank_System<<->>UBOs: VideoIdent - process
    end 

    opt SignatoryRights exchange
        Bank_System<<->>Bank_Wallet: generate request for signatory rights attestation 
        Bank_System<<->>Company_Wallet:  request & present 
        Bank_System<<->>Bank_Wallet: verification of SignatoryRights (rulebooks verification )

        critical SignatoryRights - Verification 
        Bank_System<<->>Bank_System : for each person in the signatory rights atestation
        option Person is not a legal repr. (EUCC)
            Bank_System<<->>Bank_Wallet: generate request for verification of the person 
            Bank_System<<->>Company_Wallet: request & present PoA(type: QEAA) 
            Bank_System<<->>Bank_Wallet: validate the PoA(rulebooks verification )
            Bank_System<<->>Bank_Wallet: verification of PoA Evidence against SignatoryRights
        end
    end  

    critical MVP+
        opt enhanced due diligence required 
            Bank_System<<->>Bank_Wallet: generate request for enhanced due diligence
            Bank_System<<->>Company_Wallet:  request & present 
            Bank_System<<->>Bank_Wallet: validate the EDD (rulebooks verification )
        end
        opt sanction,pep,fraud check required
            Bank_System<<->>Bank_Wallet: generate request for basic sanction list TFS 
            Bank_System<<->>Company_Wallet:  request & present 
            Bank_System<<->>Bank_Wallet: validate the TFS (rulebooks verification )
        end
        opt identification of sources required
            Bank_System<<->>Bank_Wallet: generate request for SoW
            Bank_System<<->>Company_Wallet:  request & present 
            Bank_System<<->>Bank_Wallet: validate the SoW (rulebooks verification )
        end
    end

    Bank_System<<->>Bank_System: cross check over all attestations
    Bank_System<<->>Bank_System: sign the contract 












