sequenceDiagram
    participant Seller_Bank
    participant Buyer_Wallet
    participant Buyer_VerifSystem
    participant PSP
    participant Buyer_Bank
    participant Buyer_EUDIWallet


    Buyer_Wallet->>+Buyer_Wallet:Receive e-invoice
    Buyer_Wallet->>+ Buyer_VerifSystem : notify the verification of the invoice
    Buyer_VerifSystem->>+Buyer_VerifSystem: validates the e-invoice    
    
    critical Choice of payment
    option IBAN
        Buyer_VerifSystem->>+Buyer_VerifSystem: initiate the payment 
        Buyer_VerifSystem->>+Buyer_Bank: fill the payment 
    option Card
        Buyer_VerifSystem->>+PSP: initiate the payment 
        PSP ->>+Buyer_Bank : fill the payment  
    end
    
    Buyer_Bank->>+Buyer_Bank: analse choice of payment

    critical CardPayment or Risk-Tx or Other
    option CardPayment 
        Buyer_Bank<<-->>Buyer_EUDIWallet: requests SCA
        Buyer_Bank->>+Buyer_Bank: approves SCA 
    option Other
        Buyer_Bank->>+Buyer_Bank: approves tx (token usage)
    end 
    
    Buyer_Bank<<->>Seller_Bank: sends transaction 

    critical Choice of payment
    option IBAN
        Buyer_Bank->>+Buyer_VerifSystem : send payment confirmation
        Buyer_VerifSystem->>+Buyer_VerifSystem: reconciliation e-Invoice
    option Card
        Buyer_Bank->>+PSP : send payment confirmation
        PSP->>+PSP :reconciliate e-Invoice
    end